name: schedule
description: A package to build the schedule of the communication ministry of the Evangelical Congregational Church of Vila Paraíso in Brazil.
version: 0.2.0

repository: https://github.com/zlucasmenezes/schedule

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
